name: Android Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Ruby & Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: |
          gem install fastlane

      - name: Set Gradle Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Build AAB
        run: ./gradlew bundleRelease

      - name: Deploy to Google Play (Fastlane)
        env:
          SUPPLY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON }}
        run: |
          fastlane deploy_internal
